REPO_NAME = chess_game
COMMIT_MSG = "comitted"

all: update

update:
	git add .
	git commit -m "${COMMIT_MSG}"
	git push origin main

pull:
	git pull origin main

status:
	git status

logs:
	git log --oneline

